.TH "gpio.c" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gpio.c \- This file provides code for the configuration of all used GPIO pins\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'gpio\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_GPIO_Init\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file provides code for the configuration of all used GPIO pins\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2023 STMicroelectronics\&. All rights reserved\&.
.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.SH "Function Documentation"
.PP 
.SS "void MX_GPIO_Init (void)"
Configure pins as Analog Input Output EVENT_OUT EXTI 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
