.TH "STM32G4xx_System_Private_Variables" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32G4xx_System_Private_Variables \- STM32G4xx_System_Private_Variables
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSystemCoreClock\fP = \fBHSI_VALUE\fP"
.br
.ti -1c
.RI "const uint8_t \fBAHBPrescTable\fP [16] = {0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 1U, 2U, 3U, 4U, 6U, 7U, 8U, 9U}"
.br
.ti -1c
.RI "const uint8_t \fBAPBPrescTable\fP [8] = {0U, 0U, 0U, 0U, 1U, 2U, 3U, 4U}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
