.TH "stm32g4xx_it.c" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stm32g4xx_it.c \- Interrupt Service Routines\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'stm32g4xx_it\&.h'\fP
.br
\fC#include 'adc_mes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBNMI_Handler\fP (void)"
.br
.RI "This function handles Non maskable interrupt\&. "
.ti -1c
.RI "void \fBHardFault_Handler\fP (void)"
.br
.RI "This function handles Hard fault interrupt\&. "
.ti -1c
.RI "void \fBMemManage_Handler\fP (void)"
.br
.RI "This function handles Memory management fault\&. "
.ti -1c
.RI "void \fBBusFault_Handler\fP (void)"
.br
.RI "This function handles Prefetch fault, memory access fault\&. "
.ti -1c
.RI "void \fBUsageFault_Handler\fP (void)"
.br
.RI "This function handles Undefined instruction or illegal state\&. "
.ti -1c
.RI "void \fBSVC_Handler\fP (void)"
.br
.RI "This function handles System service call via SWI instruction\&. "
.ti -1c
.RI "void \fBDebugMon_Handler\fP (void)"
.br
.RI "This function handles Debug monitor\&. "
.ti -1c
.RI "void \fBPendSV_Handler\fP (void)"
.br
.RI "This function handles Pendable request for system service\&. "
.ti -1c
.RI "void \fBSysTick_Handler\fP (void)"
.br
.RI "This function handles System tick timer\&. "
.ti -1c
.RI "void \fBDMA1_Channel1_IRQHandler\fP (void)"
.br
.RI "This function handles DMA1 channel1 global interrupt\&. "
.ti -1c
.RI "void \fBUSART2_IRQHandler\fP (void)"
.br
.RI "This function handles USART2 global interrupt / USART2 wake-up interrupt through EXTI line 26\&. "
.ti -1c
.RI "void \fBEXTI15_10_IRQHandler\fP (void)"
.br
.RI "This function handles EXTI line[15:10] interrupts\&. "
.ti -1c
.RI "void \fBTIM6_DAC_IRQHandler\fP (void)"
.br
.RI "This function handles TIM6 global interrupt, DAC1 and DAC3 channel underrun error interrupts\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "DMA_HandleTypeDef \fBhdma_adc1\fP"
.br
.ti -1c
.RI "UART_HandleTypeDef \fBhuart2\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim6\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interrupt Service Routines\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2023 STMicroelectronics\&. All rights reserved\&.
.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
