.TH "STM32G4xx_System_Private_Macros" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32G4xx_System_Private_Macros \- STM32G4xx_System_Private_Macros
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
